name = "learning-management-system"
compatibility_date = "2023-10-21"

# Cloudflare Pages configuration
pages = { project_name = "learning-management-system" }
pages_build_output_dir = "dist"

# Environment variables
[vars]
VITE_API_URL = "http://localhost:8001"

[env.production]
vars = { VITE_API_URL = "https://api.yourdomain.com" }